name: $(Date:yyyyMMdd)$(rev:.r)

trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: Yarn@3
  inputs:
    projectDirectory: 'platform-frontend'
- task: Yarn@3
  inputs:
    projectDirectory: 'platform-frontend/apps/osd-payslip'
    arguments: 'build'
